name: Generate Code Documentation

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# Change version values here
env:
  ND_VERSION: 2.2

jobs:

  generate-docs:
    name: Generate Docs
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: windows-latest

    steps:

    - name: ğŸ› Checkout
      uses: actions/checkout@v3

    - name: ğŸ’¾ Cache Natural Docs
      id: cache-nd
      uses: actions/cache@v3
      with:
        path: "Natural Docs"
        key: ${{ runner.os }}-nd-${{ env.ND_VERSION }}
    
    - name: ğŸ“¦ Install Natural docs if cache miss
      if: steps.cache-nd.outputs.cache-hit != 'true'
      run: Invoke-WebRequest -Uri "https://www.naturaldocs.org/download/natural_docs/$env:ND_VERSION/Natural_Docs_$env:ND_VERSION.zip" -OutFile "nd.zip"; tar -xf nd.zip

    - name: â˜‘ï¸ Make export location
      run: md docs
    
    - name: ğŸ§¾ Generate Docs
      shell: cmd
      run: call "Natural Docs\NaturalDocs.exe" .\.github\nd_config
    
    - name: ğŸ›  Setup Pages
      uses: actions/configure-pages@v1

    - name: â¬†ï¸ Upload artifact
      uses: actions/upload-pages-artifact@v1
      with:
        path: 'docs'

    - name: ğŸš€ Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@main