name: Lint Markdown

on:
  pull_request:
    branches: [ "main" ]

jobs:

  lint:
    strategy:
      matrix:
        repo: [ repo, wiki ]
  
    name: Lint ${{ matrix.repo }}

    runs-on: ubuntu-latest

    steps:

    # Checkout repo
    - if: matrix.repo == repo
      name: ğŸ› Checkout Repo
      uses: actions/checkout@v3

    # Checkout wiki
    - if: matrix.repo == wiki
      name: ğŸ› Checkout Wiki
      uses: actions/checkout@v3
      with:
        repository: ${{github.repository}}.wiki

    - name: â™¦ï¸ Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1.2
        bundler-cache: true

    - name: ğŸ“¦ Install dependencies
      run: gem install mdl

    - name: ğŸ§¹ Lint
      run: mdl .