name: Markdown Lint

on:
  pull_request:
    branches: [ "main" ]

jobs:

  repo:

    runs-on: ubuntu-latest

    steps:

    - name: ğŸ› Checkout
      uses: actions/checkout@v3

    - name: â™¦ï¸ Setup Ruby
      uses: ruby/setup-ruby@v1.111.0
      with:
        ruby-version: 3.1.2
        bundler-cache: true

    - name: ğŸ“¦ Install dependencies
      run: gem install mdl

    - name: ğŸ§¹ Lint
      run: mdl .


  wiki:

    runs-on: ubuntu-latest

    steps:
    
    - name: ğŸ› Checkout
      uses: actions/checkout@v3
      with:
        repository: ${{github.repository}}.wiki

    - name: â™¦ï¸ Setup Ruby
      uses: ruby/setup-ruby@v1.111.0
      with:
        ruby-version: 3.1.2
        bundler-cache: true

    - name: ğŸ“¦ Install dependencies
      run: gem install mdl

    - name: ğŸ§¹ Lint
      run: mdl .