name: Generate Documentation

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:

  generate-docs:
    
    runs-on: windows-latest

    steps:

    - name: ğŸ› Checkout
      uses: actions/checkout@v3

    - name: ğŸ’¾ Cache Natural Docs
      id: cache-nd
      uses: actions/cache@v3
      with:
        path: "Natural Docs"
        # Change key on Natural docs update
        key: ${{ runner.os }}-nd-2.2
    
    - name: ğŸ“¦ Install Natural docs if cache miss
      if: steps.cache-nd.outputs.cache-hit != 'true'
      # Change URL on Natural docs update
      run: Invoke-WebRequest -Uri "https://www.naturaldocs.org/download/natural_docs/2.2/Natural_Docs_2.2.zip" -OutFile "nd.zip"; tar -xf nd.zip

    - name: â˜‘ï¸ Make export location
      run: md docs
    
    - name: ğŸ§¾ Generate Docs
      shell: cmd
      run: call "Natural Docs\NaturalDocs.exe" .\.github\nd_config
    
    - name: â¬†ï¸ Upload Artifacts
      uses: actions/upload-artifact@v1
      with:
        name: docs
        path: docs
    
    
  deploy-docs:

    needs: [generate-docs]
    runs-on: ubuntu-latest
    steps:

      - name: ğŸ› Checkout
        uses: actions/checkout@v3

      - name: â¬‡ï¸ Download Artifacts
        uses: actions/download-artifact@v1
        with:
          name: docs

      - name: ğŸš€ Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: 'docs'